disabled_rules:
  - trailing_newline
  - force_cast
  - force_try
  - variable_name
  - cyclomatic_complexity
included:
  - Effective
  - EffectiveTests
excluded:
  - Pods

force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

line_length: 120

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string

variable_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
